title : Virtual Mesh
url: "https://virtualmesh.deltation.com/"   
theme: just-the-docs

color_scheme: dark
heading_anchors: true

exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - "*.bat"
  - "*.sh"